services:
  mcp-core-service:
    image: hoangtubk/mcp-core-service:lastest
    container_name: mcp-core-service
    environment:
      - API_KEY_WEATHER_MAP=your_api_key_here
    restart: always
    ports:
      - "8026:8026"
